---
title: "Codebuch"
author: "SNA7"
date: "1 6 2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__CODEBUCH__										
Erhebungszeitraum: seit 2000
		
Codierungsregeln:
-   Bis auf die Namen werden alle Daten numerisch erhoben.
-   Es werden keine Sonderzeichen verwendet.
-   Es werden keine Umlaute verwendet (z.B. ü=ue)
-   Die ID für die Edgelist besteht aus den Initialen der Akteure

__Edge-Attribute__											
from	
definiert den Sender in gerichteten Netzwerken. 
Entspricht ID in der Nodelist										

to 	
definiert den Empfänger in ungerichteten Netzwerken. 
Entspricht ID in der Nodelist.										

weight
Ausprägung der Kantenstärke (Beziehungsstärke), 
1 = schwach
2 = mittel
3 = stark

relationship	
definiert die Art der Beziehung; 
1 = Zusammenarbeit in Filmen/Serien 
2 = gemeinsame agentur 
3 = private Freundschaft/Verwandtschaft 
4 = gemeinsames Video										
											
__Node-Attribute__											
id	
eindeutige Identifikation jedes einzelnen Knotens; 
ein Wort; 
keine Sonderzeichen										

name	
vollständiger Namen des Akteurs										

sex	
1 = male 
2 = female

job title	
1 = Schauspieler:in 
2 = Regisseur:in 
3 = beides

films	
definiert die Bekanntheit der Akteure, gemessen an der Anzahl der gespielten Filme/Serien						
1 = 0-20 
2 = 21-35 
3 = 36-50
4 = über 50			


video	
Ist der Beitrag zu #allesdichtmachen des Akteurs noch offline oder wurde zurückgezogen. 
1 = online; 
2 = offline		

range	
definiert die Reichweite der Akteure, bezogen auf die Aufrufe ihres YouTube-Beitrags zu #allesdichtmachen						
1 = <100.000 
2 = 100.000-300.000
3 = 300.001-500.000
4 = >500.000				

querdenker	
Finden sich offensichtliche Verbinungen zu Querdenkern, 
1 = ja 
2 = nein										
											
											
NA	
definiert fehlende Werte, bei der Datenerhebung das Feld einfach weglassen.										
											